# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows Client

on:
   workflow_dispatch: null

jobs:
   build:

      runs-on: windows-latest
      steps:

      -  uses: actions/checkout@v3

      -  name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt

      -  name: Build with Maven
         run: |
            mvn install --batch-mode --update-snapshots package
            cd engine
            mvn install --batch-mode --update-snapshots package
            cd ../core
            mvn install --batch-mode --update-snapshots package
            cd ../desktop
            mvn install --batch-mode --update-snapshots package

      -  name: Upload MSI
         uses: actions/upload-artifact@v2
         with:
            name: MSI file
            path: desktop/target/installer/*.msi