name: Java CI

on:

- push
jobs:
   build:

      runs-on: windows-latest
      steps:
      -  uses: actions/checkout@v3
      -  name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt
      -  name: Build with Maven
         run: mvn --batch-mode --update-snapshots package
      -  name: Upload MSI
         uses: actions/upload-artifact@v2
         with:
            name: MSI file
            path: target/installer/*.msi