# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Linux Client

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Install binutils
      run: sudo apt-get install binutils
    - name: Install fakeroot
      run: sudo apt-get install fakeroot
    - name: Build with Maven
      run: mvn verify --batch-mode --update-snapshots package
    - name: Upload DEB package
      uses: actions/upload-artifact@v2
      with:
        name: DEB files
        path: target/installer/*.deb
    - name: Upload DEB package
      uses: actions/upload-artifact@v2
      with:
        name: DEB files
        path: target/installer/*.deb
