# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
   push:
# Sequence of patterns matched against refs/tags
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release_pluvia

jobs:
   build:
      name: Create Release
      runs-on: self-hosted
      steps:
      -  name: Checkout code
         uses: actions/checkout@v3
      -  name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt
      -  name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
         with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
               TBD
            draft: false
            prerelease: false
   build_windows:
      name: buid_windows_version
      runs-on: self-hosted
      steps:
      -  name: Checkout code
         uses: actions/checkout@v3
      -  name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt
      -  name: Build with Maven
         run: mvn verify --batch-mode --update-snapshots package
      -  name: upload MSI
         uses: actions/upload-release-asset@v1
         env:
            GITHUB_TOKEN: ${{ github.token }}
         with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./target/installer/*.msi
            asset_name: pluvia.msi
            asset_content_type: application/vnd.apple.installer+xml
