# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
   push:
      tags:
# Sequence of patterns matched against refs/tags
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

name: release-pluvia

jobs:
   create-release-job:
      name: create-release-job
      runs-on: self-hosted
      outputs:
         output1: ${{ steps.create_release.outputs.upload_url }}
      steps:
      -  name: checkout-code-step
         uses: actions/checkout@v3
      -  name: set-up-jdk-17-step
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt
      -  name: create-release-step
         id: create_release
         uses: actions/create-release@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
         with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
               TBD
            draft: false
            prerelease: false
   build-windows-job:
      name: build-windows-job
      runs-on: self-hosted
      needs: create-release-job
      steps:
      -  name: checkout-code-step
         uses: actions/checkout@v3
      -  name: set-up-jdk-17-step
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: adopt
      -  name: build-with-maven-step
         run: mvn verify --batch-mode --update-snapshots package
      -  name: upload-msi-step
         uses: actions/upload-release-asset@v1
         env:
            GITHUB_TOKEN: ${{ github.token }}
         with:
            upload_url: ${{ needs.create-release-job.outputs.output1 }}
            asset_path: ./target/installer/*.msi
            asset_name: pluvia.msi
            asset_content_type: application/vnd.apple.installer+xml